### ISSUE TITLE
 Self-signed SAML keys are not automatically generated on first container startup. 

### ISSUE THREAD

**Issue by M0Rf30** [WeblateOrg/docker#1078]
`/app/data/ssl/saml.crt`
&
`/app/data/ssl/saml.key`

are not generated at first startup time as declared in documentation

https://github.com/WeblateOrg/weblate/blob/8fcbfa57a670307633cbccad46531741a9aa2830/docs/admin/install/docker.rst#L980

or at least I can't find a code instruction that manage this

**Comment by nijel** [comment]
The file is generated here:

https://github.com/WeblateOrg/docker/blob/1a259d76f1e26bbb564fa9a0ef0c5f3052bdeeae/start#L192-L204

> If could help, also this test
> https://github.com/WeblateOrg/docker-compose/blob/d5aab0bc066139a508e7d00ebfc4b34b955a4c9d/test-saml#L2
> can't work without an in-place saml.crt

This is a *test* that checks the file is present, so it's expected to fail in case it is not there (but it does not, see https://github.com/WeblateOrg/docker/runs/2566988768?check_suite_focus=true#step:16:1).

**Comment by M0Rf30** [comment]
ok, my fault. I'll close this

**Comment by nijel** [comment]
`runserver` is the default container command:

https://github.com/WeblateOrg/docker/blob/1a259d76f1e26bbb564fa9a0ef0c5f3052bdeeae/Dockerfile#L191

It takes care of database migrations and other things which are necessary on the container startup.

I just did installation following instructions on https://docs.weblate.org/en/latest/admin/install/docker.html#installation and the key is generated during the startup:

```
weblate_1   | Generating a RSA private key
weblate_1   | ...................................................................++++
weblate_1   | ...................................++++
weblate_1   | writing new private key to '/app/data/ssl/saml.key'
weblate_1   | -----
```

And the keys are indeed present:

```
# find /var/lib/docker/volumes/wl-test_weblate-data/_data/ssl/
/var/lib/docker/volumes/wl-test_weblate-data/_data/ssl/
/var/lib/docker/volumes/wl-test_weblate-data/_data/ssl/saml.key
/var/lib/docker/volumes/wl-test_weblate-data/_data/ssl/saml.crt
```

Do you get any error during the container startup? How do you run it?

**Comment by M0Rf30** [comment]
I only changed the volumes:
```
volumes:
  weblate-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/srv/docker/weblate"
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/srv/docker/postgres"
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/srv/docker/redis"
```
I don't test with `set -x` flag. But generating the saml material outside of an if do the trick for sure.
I prepared a PR for this
