### ISSUE TITLE
Cannot run container

### ISSUE THREAD

**Issue by Insoleet** [WeblateOrg/docker#117]
Hi,

I'm trying to deploy weblate using the docker container. The behaviour is somewhat weird : 

```
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up
Starting weblatedocker_database_1
Starting weblatedocker_cache_1
Recreating weblatedocker_weblate_1
Attaching to weblatedocker_cache_1, weblatedocker_database_1, weblatedocker_weblate_1
cache_1     | 1:C 25 Jan 18:09:36.583 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1     | 1:C 25 Jan 18:09:36.583 # Redis version=4.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1     | 1:C 25 Jan 18:09:36.583 # Configuration loaded
cache_1     | 1:M 25 Jan 18:09:36.585 * Running mode=standalone, port=6379.
cache_1     | 1:M 25 Jan 18:09:36.585 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cache_1     | 1:M 25 Jan 18:09:36.585 # Server initialized
cache_1     | 1:M 25 Jan 18:09:36.585 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache_1     | 1:M 25 Jan 18:09:36.585 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
cache_1     | 1:M 25 Jan 18:09:36.788 * DB loaded from append only file: 0.203 seconds
cache_1     | 1:M 25 Jan 18:09:36.788 * Ready to accept connections
database_1  | LOG:  database system was shut down at 2019-01-25 18:02:49 UTC
database_1  | LOG:  MultiXact member wraparound protections are now enabled
database_1  | LOG:  database system is ready to accept connections
database_1  | LOG:  autovacuum launcher started
weblate_1   | Postgres is up
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
weblate_1   | Running migrations:
weblate_1   |   No migrations to apply.
weblate_1   | 
weblate_1   | 0 static files copied to '/app/data/static', 195 unmodified.
database_1  | ERROR:  duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
database_1  | DETAIL:  Key (email)=(noreply@weblate.org) already exists.
database_1  | STATEMENT:  INSERT INTO "weblate_auth_user" ("password", "last_login", "username", "full_name", "email", "is_superuser", "is_active", "date_joined") VALUES ('pbkdf2_sha256$120000$RTZXTbuj63Ga$TxBoHxJFd73CqL75mX0FjSdtx+gbxkVGgL3dO26ar8U=', NULL, 'admin', '', 'noreply@weblate.org', false, true, '2019-01-25T18:09:56.125683+00:00'::timestamptz) RETURNING "weblate_auth_user"."id"
weblate_1   | ERROR Handled exception IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
weblate_1   | DETAIL:  Key (email)=(noreply@weblate.org) already exists.
weblate_1   | 
weblate_1   | Creating user admin
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   | psycopg2.IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
weblate_1   | DETAIL:  Key (email)=(noreply@weblate.org) already exists.
weblate_1   | 
weblate_1   | 
weblate_1   | The above exception was the direct cause of the following exception:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/runner.py", line 34, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/auth/management/commands/createadmin.py", line 107, in handle
weblate_1   |     password
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/auth/models.py", line 222, in create_user
weblate_1   |     return self._create_user(username, email, password, **extra_fields)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/auth/models.py", line 217, in _create_user
weblate_1   |     user.save(using=self._db)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/auth/models.py", line 405, in save
weblate_1   |     super(User, self).save(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/base_user.py", line 73, in save
weblate_1   |     super().save(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 718, in save
weblate_1   |     force_update=force_update, update_fields=update_fields)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 748, in save_base
weblate_1   |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 831, in _save_table
weblate_1   |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 869, in _do_insert
weblate_1   |     using=using, raw=raw)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
weblate_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1136, in _insert
weblate_1   |     return query.get_compiler(using=using).execute_sql(return_id)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
weblate_1   |     cursor.execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 100, in execute
weblate_1   |     return super().execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 68, in execute
weblate_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
weblate_1   |     return executor(sql, params, many, context)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
weblate_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   | django.db.utils.IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
weblate_1   | DETAIL:  Key (email)=(noreply@weblate.org) already exists.
weblate_1   | 
```

I got these two docker-compose.yml files : 
```
cat docker-compose.yml 
version: '2'
services:
  weblate:
    image: weblate/weblate
    links:
      - database
      - cache
    ports:
      - 10080:80
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

And also : 

``` 
version: '2'
services:
  weblate:
    environment:
      - WEBLATE_EMAIL_HOST=smtp.example.com
      - WEBLATE_EMAIL_HOST_USER=user
      - WEBLATE_EMAIL_HOST_PASSWORD=pass
      - WEBLATE_SERVER_EMAIL=weblate@co.tools
      - WEBLATE_DEFAULT_FROM_EMAIL=weblate@co.tools
      - WEBLATE_ALLOWED_HOSTS=weblate.co.tools, localhost
      - WEBLATE_ADMIN_PASSWORD=someadminpassword
```

The containers is locked in a loop printing this insert error.

Any idea ?

Thanks for your work.
