### ISSUE TITLE
redis is unavailable for KeyError: 'WEBLATE_ADMIN_EMAIL'

### ISSUE THREAD

**Issue by xerenahmed** [WeblateOrg/docker#1231]
```
weblate-weblate-1   | Traceback (most recent call last):
weblate-weblate-1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate-weblate-1   |     sys.exit(main())
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/runner.py", line 36, in main
weblate-weblate-1   |     from weblate.utils.errors import report_error
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/utils/errors.py", line 31, in <module>
weblate-weblate-1   |     import weblate.utils.version
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/utils/version.py", line 23, in <module>
weblate-weblate-1   |     from weblate.vcs.base import RepositoryException
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/vcs/base.py", line 38, in <module>
weblate-weblate-1   |     from weblate.utils.lock import WeblateLock
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/utils/lock.py", line 23, in <module>
weblate-weblate-1   |     from django_redis.cache import RedisCache
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/django_redis/cache.py", line 12, in <module>
weblate-weblate-1   |     DJANGO_REDIS_SCAN_ITERSIZE = getattr(settings, "DJANGO_REDIS_SCAN_ITERSIZE", 10)
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/django/conf/__init__.py", line 82, in __getattr__
weblate-weblate-1   |     self._setup(name)
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/django/conf/__init__.py", line 69, in _setup
weblate-weblate-1   |     self._wrapped = Settings(settings_module)
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/django/conf/__init__.py", line 170, in __init__
weblate-weblate-1   |     mod = importlib.import_module(self.SETTINGS_MODULE)
weblate-weblate-1   |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
weblate-weblate-1   |     return _bootstrap._gcd_import(name[level:], package, level)
weblate-weblate-1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/settings_docker.py", line 53, in <module>
weblate-weblate-1   |     ADMINS = ((os.environ["WEBLATE_ADMIN_NAME"], os.environ["WEBLATE_ADMIN_EMAIL"]),)
weblate-weblate-1   |   File "/usr/lib/python3.9/os.py", line 679, in __getitem__
weblate-weblate-1   |     raise KeyError(key) from None
weblate-weblate-1   | KeyError: 'WEBLATE_ADMIN_EMAIL'
weblate-weblate-1   | redis is unavailable - waiting 18
```

**Describe the issue**

redis is unavailable for KeyError: 'WEBLATE_ADMIN_EMAIL'

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] remove compose volumes

**To Reproduce the issue**

1. docker compose up

my docker-compose.yml file:
```
version: "3"

services:
  weblate:
    image: weblate/weblate
    tmpfs:
      - /app/cache
    volumes:
      - ./data/weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    ports:
      - 80:8080

  database:
    image: postgres:13-alpine
    env_file:
      - ./environment
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
```
