### ISSUE TITLE
Stable mount point for legal documents

### ISSUE THREAD

**Issue by sr258** [WeblateOrg/docker#1342]
### Describe the problem

I use the docker container in a docker-compose setup and mount in the legal documents with a volume like this:

```yaml
  weblate:
    image: weblate/weblate:4.10.1-1
    volumes:
      - ./data/documents:/usr/local/lib/python3.10/site-packages/weblate/legal/templates/legal/documents
```

Unfortunately, the exact mount point inside the container changes with python releases. In 4.9 the path was like this:

```
/usr/local/lib/python3.9/dist-packages/weblate/legal/templates/legal/documents
```

In 4.10 it has become:

```
/usr/local/lib/python3.10/site-packages/weblate/legal/templates/legal/documents
```

### Describe the solution you'd like

There should be a mount point like /legal that you can use to map in volumes that is stable regardless of the Python version.
