### ISSUE TITLE
Feature: Easy method to add trusted CA Certificate in containerized installation

### ISSUE THREAD

**Issue by clawoflight** [WeblateOrg/docker#1525]
### Describe the problem

Your recommendation for handling private CAs is to trust them system-wide. This is a perfectly normal practice for system-wide installations. However, that would require building custom docker images for many on-prem installations, which brings a lot of maintenance overhead.
IMHO this is something that the weblate docker image should support. We certainly do this for our products :)

### Describe the solution you'd like

Proposal: A simple environment variable that we could set with a path to a CA certificate.
The entrypoint of the docker image could then add it to the CA bundle itself.

This makes it easy to mount in a CA cert from a volume, as a Kubernetes secret object, etc.

**Comment by FSeidinger-XI** [comment]
The easiest way is to map a certificate bundle (single pem file with all needed certificates) into the container to `/etc/ssl/ca-bundle.pem`. This part gives Python the right ca bundle for the `requests`.

For the certificates used by the system trust store, the ca bundle is exploded into `/etc/ssl/certs`. At least with helm and kubernetes it is done like that. The `subpath` element does the exploding and creates the symbolic links to the system trust store.

```
extraVolumes:
  - configMap:
      name: ca-bundle
    name: ca-bundle

extraVolumeMounts:
  - mountPath: /etc/ssl/certs
    name: ca-bundle
  - mountPath: /etc/ssl/ca-bundle.pem
    name: ca-bundle
    subPath: ca-certificates.crt
```

Maybe this works for plain docker or docker compose also.
