### ISSUE TITLE
Gitlab Auth

### ISSUE THREAD

**Issue by ochorocho** [WeblateOrg/docker#225]
Hey,

i want to enable social auth for gitlab
i followed the instuctions described [here](https://docs.weblate.org/en/latest/admin/deployments.html#gitlab) and added the variables to my `docker-compose.override.yml`:

```
      - WEBLATE_SOCIAL_AUTH_GITLAB_KEY = 'XXX'
      - WEBLATE_SOCIAL_AUTH_GITLAB_SECRET = 'XXX'
      - WEBLATE_SOCIAL_AUTH_GITLAB_SCOPE = ['api']
      - WEBLATE_SOCIAL_AUTH_GITLAB_API_URL = 'https://gitlab.domain.org/'
```

After that i removed and rebuild the container:
```
docker-composer rm
docker-compose -f docker-compose.yml -f docker-compose.override.yml build
docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
```

The variables show up using `printenv` in the container but the Social Login is not displayed on the login screen.

How do i enable social login to show up in the interface?

**Comment by ochorocho** [comment]
Thanks for your answer.

`WEBLATE_AUTH_LDAP_SERVER_URI` ist not enabled.
iirc, `WEBLATE_AUTH_LDAP_SERVER_URI` is and was commented out by default.

**Comment by nijel** [comment]
Do you have anything in `/app/data/settings-override.py`? Also what version of the image do you run?

**Comment by ochorocho** [comment]
`/app/data/settings-override.py` does not exist in the container.
Weblate version is 3.6.1

![Bildschirmfoto 2019-05-16 um 11 41 14](https://user-images.githubusercontent.com/4623070/57844043-91d37200-77cf-11e9-9f26-723cdcf7ecc1.png)

**Comment by nijel** [comment]
Can you try placing following code to `/app/data/settings-override.py` in the container? It should print what is actually configured:

```python
import os
from pprint import pprint
pprint(dict(os.environ))
pprint(AUTHENTICATION_BACKENDS)
```

**Comment by ochorocho** [comment]
Sorry for the late reply.

Added the code to settings-override.py:

```
# cat /app/data/settings-override.py 
import os
from pprint import pprint
pprint(dict(os.environ))
pprint(AUTHENTICATION_BACKENDS)
```

But i'm not getting any output.

![Bildschirmfoto 2019-05-21 um 18 51 14](https://user-images.githubusercontent.com/4623070/58115029-761a0280-7bf9-11e9-9654-01faa0e0c38b.png)

**Comment by nijel** [comment]
It should be on container stdout, not visible in the app.

**Comment by ochorocho** [comment]
This is the output:
```
{'DJANGO_IS_MANAGEMENT_COMMAND': '1',
 'DJANGO_SETTINGS_MODULE': 'weblate.settings',
 'HOME': '/root',
 'HOSTNAME': '402c174b18ff',
 'LANG': 'C.UTF-8',
 'LC_ALL': 'C.UTF-8',
 'LOGNAME': 'weblate',
 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'PGSSLMODE': 'prefer',
 'POSTGRES_DATABASE': 'weblate',
 'POSTGRES_HOST': 'database',
 'POSTGRES_PASSWORD': 'weblate',
 'POSTGRES_PORT': '',
 'POSTGRES_SSL_MODE': 'prefer',
 'POSTGRES_USER': 'weblate',
 'PWD': '/',
 'REDIS_HOST': 'cache',
 'REDIS_PORT': '6379',
 'SHELL': '/bin/sh',
 'SUDO_COMMAND': '/usr/local/bin/weblate migrate',
 'SUDO_GID': '0',
 'SUDO_UID': '0',
 'SUDO_USER': 'root',
 'TERM': 'unknown',
 'USER': 'weblate',
 'VERSION': '3.6.1',
 'WEBLATE_ADMIN_EMAIL': 'weblate@example.com',
 'WEBLATE_ADMIN_NAME': 'Weblate Admin',
 'WEBLATE_ADMIN_PASSWORD': 'XXXXXXXXXXX',
 'WEBLATE_ALLOWED_HOSTS': 'translate.zeroseven.de',
 'WEBLATE_CMD': '/usr/local/bin/weblate',
 'WEBLATE_DEBUG': '1',
 'WEBLATE_DEFAULT_FROM_EMAIL': 'weblate@example.com',
 'WEBLATE_EMAIL_HOST': 'zeroseven.de',
 'WEBLATE_EMAIL_HOST_PASSWORD': '_Password-123_',
 'WEBLATE_EMAIL_HOST_USER': 'team@zeroseven.de',
 'WEBLATE_EMAIL_PASSWORD': '',
 'WEBLATE_EMAIL_USER': '',
 'WEBLATE_IP_PROXY_HEADER': 'HTTP_X_FORWARDED_FOR',
 'WEBLATE_LOGLEVEL': 'DEBUG',
 'WEBLATE_REGISTRATION_OPEN': '0',
 'WEBLATE_REQUIRE_LOGIN': '1',
 'WEBLATE_SERVER_EMAIL': 'weblate@example.com',
 'WEBLATE_SITE_TITLE': 'Weblate'}
```

This is sent to stdout 6 times during boot up of the container.

**Comment by nijel** [comment]
It seems that the `WEBLATE_SOCIAL_AUTH_GITLAB_*` variables are not set in the container. How does the `docker-compose.override.yml` look?

**Comment by ochorocho** [comment]
Here the entire `docker-compose.override.yml` : 

```
version: '3'
services:
  weblate:
    ports:
      - 8082:80
    environment:
      - WEBLATE_REGISTRATION_OPEN=0
      - WEBLATE_EMAIL_HOST=domain.de
      - WEBLATE_EMAIL_HOST_USER=team@domain.de
      - WEBLATE_EMAIL_HOST_PASSWORD=_Password-123_
      - WEBLATE_ALLOWED_HOSTS=weblate.domain.de
      - WEBLATE_ADMIN_PASSWORD=XXXXXX
      - WEBLATE_REQUIRE_LOGIN=1
      - WEBLATE_IP_PROXY_HEADER=HTTP_X_FORWARDED_FOR
      - WEBLATE_SOCIAL_AUTH_GITLAB_KEY = 'XXXXXXX'
      - WEBLATE_SOCIAL_AUTH_GITLAB_SECRET = 'XXXXXXX'
      - WEBLATE_SOCIAL_AUTH_GITLAB_SCOPE = ['api']
      - WEBLATE_SOCIAL_AUTH_GITLAB_API_URL = 'https://gitlab.domain.de/'
    volumes:
      - ../weblate-data:/app/data
  database:
    volumes:
      - ../weblate-db:/var/lib/postgresql/data
```
