### ISSUE TITLE
Weblate cannot start container in docker swarm mode

### ISSUE THREAD

**Issue by FSeidinger-XI** [WeblateOrg/docker#2816]
### Describe the issue

I use the official docker image with a compose file in docker swarm. In this context the container cannot start, due to permissions issues regarding them tmpfs mounts.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create a compose file on base of the official weblate docker-compose file.
2. Deploy the weblate stack in docker swarm with `docker stack deploy weblate -c compose.yml`
3. See with `docker stack ps weblate` that the weblate container does not come up. The redis and postgres containers however are starting fine.
4. See the log outputs for the weblate container:

```
weblate_weblate.1.i53r2717rrgi@bosmang    | Starting Weblate 5.8.3...
weblate_weblate.1.i53r2717rrgi@bosmang    | /app/bin/start: 111: cannot create /tmp/localtime: Read-only file system
```

### Expected behavior

The container should start and maybe fix the permissions upon start.

### How do you run Weblate?

Other

### Weblate versions

Latest 5.8 on docker ce engine version 27.3.1

### Additional context

The docker compose file reference for docker swarm mode (docker stack deploy) is different to the local container (docker compose). In swarm mode there is no way of configuring the uid or gid for the mounted tmpfs file system.

I use the following compose file:

```
networks:
  weblate:

volumes:
  weblate-postgres-data:
    external: true

  weblate-redis-data:
    external: true

  weblate-data:
    external: true

  weblate-cache:
    external: true

services:
  database:
    image: postgres:17-alpine
  
    networks:
      - weblate

    volumes:
      - weblate-postgres-data:/var/lib/postgresql/data

    env_file:
      - /srv/cloud/weblate/environment

    deploy:
      placement:
        constraints:
          - node.role != manager

  cache:
    image: redis:7-alpine

    networks:
      - weblate

    volumes:
    - weblate-redis-data:/data

    command: [redis-server, --save, '60', '1']

    deploy:
      placement:
        constraints:
          - node.role != manager

  weblate:
    image: weblate/weblate:5.8

    networks:
      - weblate
  
    volumes:
      - weblate-data:/app/data
      - weblate-cache:/app/cache     
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run

    env_file:
      - /srv/cloud/weblate/environment

    depends_on:
    - database
    - cache

    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.capacity != small
```
