### ISSUE TITLE
[5.8.4] Unable to start with a read-only fs (except /app/data)

### ISSUE THREAD

**Issue by gourvy** [WeblateOrg/docker#2923]
### Describe the issue

I use an instance of Weblate in kubernetes, with kustomize instead of helm. I tried to upgrade from 5.7.2.2 to 5.8.4.1 but got a problem:

```
Starting Weblate 5.8.4...
System check identified no issues (2 silenced).
Postgres 170000 is up
mkdir: cannot create directory ‘/run/supervisor.conf.d/’: Read-only file system
```
and the pod/container stops here. No problem with version 5.8.3.1.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Using the helm chart, I think it's reproducible with a small modification of the deployment:
```
spec:
  template:
    spec:
      containers:
        - name: weblate
        securityContext:
          readOnlyRootFilesystem: true
```
Or, with docker, I guess starting the container with a read-only fs should do the trick.

### Expected behavior

Either update the helm chart to mount /run (and /tmp) as a tmpfs or fix the issue (I don't know how).

### Additional context

I think the problem was introduced with this commit: https://github.com/WeblateOrg/docker/commit/0b02c627f51ba6a01bbd56a442a948227f0318ba or the previous one.

Linked issue: https://github.com/WeblateOrg/docker/issues/2816
The last comment seems to match:
> The tmpfs is only needed with a read-only file system. So, IMHO the only problem are additional volumes which are not supposed to be used as real volumes. I think https://github.com/WeblateOrg/docker/pull/2821 should address the issue by removing the additional volumes. Let's see if the tests pass there and it doesn't break any of the existing expectations.

**Comment by nijel** [comment]
tmpfs is needed on `/tmp` and `/run` when using a read-only file system, as documented in https://docs.weblate.org/en/latest/admin/install/docker.html#docker-container-volumes.

0b02c627f51ba6a01bbd56a442a948227f0318ba just removes explicit volumes for these locations as these are not needed when not using read-only file system and cause issues in swarm mode as described in https://github.com/WeblateOrg/docker/issues/2816.

**Comment by gourvy** [comment]
Thank you! After modifying my deployment
```
spec:
  template:
    spec:
      containers:
      - name: weblate
        volumeMounts:
        - mountPath: /app/cache
          name: weblate-cache
        - mountPath: /run
          name: weblate-run
        - mountPath: /tmp
          name: weblate-tmp
      volumes:
      - name: weblate-cache
        emptyDir: {}
      - name: weblate-run
        emptyDir: {}
      - name: weblate-tmp
        emptyDir: {}
```
it works fine :)
