### ISSUE TITLE
docker-compose up is not work

### ISSUE THREAD

**Issue by lighter** [WeblateOrg/docker#45]
when I restart the weblate docker, I got the error message form weblate container. I didn't upgrade my postgres, and I used 9.4.

```
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
weblate_1   |     fake_initial=fake_initial,
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
weblate_1   |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
weblate_1   |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
weblate_1   |     state = migration.apply(state, schema_editor)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
weblate_1   |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
weblate_1   |     self.code(from_state.apps, schema_editor)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/permissions/migrations/0006_auto_20170404_1637.py", line 19, in migrate_acl
weblate_1   |     emit_post_migrate_signal(0, False, schema_editor.connection.alias)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
weblate_1   |     **kwargs
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 193, in send
weblate_1   |     for receiver in self._live_receivers(sender)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/permissions/models.py", line 163, in sync_create_groups
weblate_1   |     create_groups(False)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/permissions/models.py", line 141, in create_groups
weblate_1   |     settings.ANONYMOUS_USER_NAME,
weblate_1   | ValueError: Anonymous user (anonymous) already exists and enabled, please change ANONYMOUS_USER_NAME setting.
weblate_1   |   Applying permissions.0006_auto_20170404_1637...
weblate_1   | Postgres is up
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, admin, auth, authtoken, contenttypes, gitexport, lang, permissions, screenshots, sessions, sites, social_django, trans
weblate_1   | Running migrations:
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/runner.py", line 33, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
weblate_1   |     fake_initial=fake_initial,
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
weblate_1   |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
weblate_1   |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
weblate_1   |     state = migration.apply(state, schema_editor)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
weblate_1   |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
weblate_1   |     self.code(from_state.apps, schema_editor)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/permissions/migrations/0006_auto_20170404_1637.py", line 19, in migrate_acl
weblate_1   |     emit_post_migrate_signal(0, False, schema_editor.connection.alias)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
weblate_1   |     **kwargs
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 193, in send
weblate_1   |     for receiver in self._live_receivers(sender)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/permissions/models.py", line 163, in sync_create_groups
weblate_1   |     create_groups(False)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/permissions/models.py", line 141, in create_groups
weblate_1   |     settings.ANONYMOUS_USER_NAME,
weblate_1   | ValueError: Anonymous user (anonymous) already exists and enabled, please change ANONYMOUS_USER_NAME setting.
weblate_1   |   Applying permissions.0006_auto_20170404_1637...
```

This is my docker-compse.yml

```
version: '2'
services:
  weblate:
    image: weblate/weblate
    links:
      - database
      - cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./weblate/environment
    restart: always
    depends_on:
      - database
      - cache
  web:
    build: nginx
    links:
      - weblate
    ports:
      - "9112:80"
    volumes_from:
      - weblate:ro
    restart: always
    depends_on:
      - weblate
  database:
    image: postgres:9.4
    env_file:
      - ./weblate/environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: memcached:1.4
    restart: always
volumes:
  weblate-data: {}
  postgres-data: {}
```
