### ISSUE TITLE
Inaccessible login page when running under path and WEBLATE_REQUIRE_LOGIN=1

### ISSUE THREAD

**Issue by belicekm** [WeblateOrg/docker#462]
Hello,

opening weblate under a path `/weblate` with environment variable `WEBLATE_REQUIRE_LOGIN=1`  is causing many "looped redirects" in nginx. The request eventually fails with `502 Bad Gateway`.

### Expected behavior
login page will be displayed

### Steps to reproduce
- pull the image 
- in `docker-compose.override.yml` set environment variable `WEBLATE_URL_PREFIX: /weblate`
- enable `WEBLATE_REQUIRE_LOGIN=1` in the `environment` file
- `docker-compose up -d weblate`
- open web browser and navigate to `localhost/weblate`
- there will be many redirects followed by nginx reporting `502 Bad Gateway`

### My image version
`weblate/weblate              latest              e7671060ee82        5 weeks ago         692MB`

### My docker-compose.override.yml
```
version: '3'
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_EMAIL_HOST: smtp.example.com
      WEBLATE_EMAIL_HOST_USER: admin
      WEBLATE_EMAIL_HOST_PASSWORD: admin
      WEBLATE_SERVER_EMAIL: weblate@example.com
      WEBLATE_DEFAULT_FROM_EMAIL: weblate@example.com
      WEBLATE_ALLOWED_HOSTS: weblate.example.com,localhost,192.168.6.75
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_ADMIN_EMAIL: weblate.admin@example.com      
      WEBLATE_URL_PREFIX: /weblate
```

### This is how the url looks like at the end
```
http://192.168.6.75/weblate/accounts/login/?next=/weblate/accounts/login/%3Fnext%3D/weblate/accounts/login/%253Fnext%253D/weblate/accounts/login/%25253Fnext%25253D/weblate/accounts/login/%2525253Fnext%2525253D/weblate/accounts/login/%252525253Fnext%252525253D/weblate/accounts/login/%25252525253Fnext%25252525253D/weblate/accounts/login/%2525252525253Fnext%2525252525253D/weblate/accounts/login/%252525252525253Fnext%252525252525253D/weblate/accounts/login/%25252525252525253Fnext%25252525252525253D/weblate/accounts/login/%2525252525252525253Fnext%2525252525252525253D/weblate/accounts/login/%252525252525252525253Fnext%252525252525252525253D/weblate/accounts/login/%25252525252525252525253Fnext%25252525252525252525253D/weblate/accounts/login/%2525252525252525252525253Fnext%2525252525252525252525253D/weblate/accounts/login/%252525252525252525252525253Fnext%252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525253Fnext%25252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525253Fnext%2525252525252525252525252525253D/weblate/accounts/login/%252525252525252525252525252525253Fnext%252525252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525252525253Fnext%25252525252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525252525253Fnext%2525252525252525252525252525252525253D/weblate/accounts/login/%252525252525252525252525252525252525253Fnext%252525252525252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525252525252525253Fnext%25252525252525252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525252525252525253Fnext%2525252525252525252525252525252525252525253D/weblate/accounts/login/%252525252525252525252525252525252525252525253Fnext%252525252525252525252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525252525252525252525253Fnext%25252525252525252525252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525252525252525252525253Fnext%2525252525252525252525252525252525252525252525253D/weblate/accounts/login/%252525252525252525252525252525252525252525252525253Fnext%252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525252525252525252525252525253Fnext%25252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525252525252525252525252525253Fnext%2525252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%252525252525252525252525252525252525252525252525252525253Fnext%252525252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525252525252525252525252525252525253Fnext%25252525252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525252525252525252525252525252525253Fnext%2525252525252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%252525252525252525252525252525252525252525252525252525252525253Fnext%252525252525252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%25252525252525252525252525252525252525252525252525252525252525253Fnext%25252525252525252525252525252525252525252525252525252525252525253D/weblate/accounts/login/%2525252525252525252525252525252525252525252525252525252525252525253Fnext%2525252525252525252525252525252525252525252525252525252525252525253D/weblate/
```

It would be very helpful if You could do something about this.
In any case keep up the good work.
