### ISSUE TITLE
Custom certificate not taken into account for Social Auth Keycloak

### ISSUE THREAD

**Issue by mleneveut** [WeblateOrg/docker#477]
Hi,

I configured the Keycloak social Auth, and when login with Keycloak I got this error : 

```
uwsgi stderr | ERROR Handled exception: AuthFailed: Authentication failed: HTTPSConnectionPool(host='keycloak.is4.local', port=443): Max retries exceeded with url: /auth/realms/develop/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))
uwsgi stderr | [pid: 407|app: 0|req: 53/161] 10.0.2.189 () {62 vars in 2668 bytes} [Thu Dec 12 10:19:39 2019] GET /accounts/complete/keycloak/?redirect_state=YXgvM7wSIIvPl94Mqted863WeiDOuRVt&state=YXgvM7wSIIvPl94Mqted863WeiDOuRVt&session_state=4a623e35-2d79-4b7a-a68d-50742930ac59&code=c05e4c34-6fc3-4b12-bdf9-c200532366b1.4a623e35-2d79-4b7a-a68d-50742930ac59.686badf8-43b8-497b-8dac-028613058a6b => generated 0 bytes in 1820 msecs (HTTP/1.1 302) 13 headers in 1003 bytes (1 switches on core 0)
nginx stdout | 10.0.2.189 - - [12/Dec/2019:10:19:40 +0000] "GET /accounts/complete/keycloak/?redirect_state=YXgvM7wSIIvPl94Mqted863WeiDOuRVt&state=YXgvM7wSIIvPl94Mqted863WeiDOuRVt&session_state=4a623e35-2d79-4b7a-a68d-50742930ac59&code=c05e4c34-6fc3-4b12-bdf9-c200532366b1.4a623e35-2d79-4b7a-a68d-50742930ac59.686badf8-43b8-497b-8dac-028613058a6b HTTP/1.1" 302 0 "https://keycloak.is4.local/auth/realms/develop/protocol/openid-connect/auth?client_id=weblate&redirect_uri=https%3A%2F%2Fci-weblate.mycompany.com%2Faccounts%2Fcomplete%2Fkeycloak%2F%3Fredirect_state%3DYXgvM7wSIIvPl94Mqted863WeiDOuRVt&state=YXgvM7wSIIvPl94Mqted863WeiDOuRVt&response_type=code" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
uwsgi stderr | [pid: 406|app: 0|req: 6/162] 10.0.2.189 () {62 vars in 2371 bytes} [Thu Dec 12 10:19:41 2019] GET /accounts/login/ => generated 8171 bytes in 1691 msecs (HTTP/1.1 200) 12 headers in 772 bytes (1 switches on core 0)
nginx stdout | 10.0.2.189 - - [12/Dec/2019:10:19:42 +0000] "GET /accounts/login/ HTTP/1.1" 200 3003 "https://keycloak.is4.local/auth/realms/develop/protocol/openid-connect/auth?client_id=weblate&redirect_uri=https%3A%2F%2Fci-weblate.mycompany.com%2Faccounts%2Fcomplete%2Fkeycloak%2F%3Fredirect_state%3DYXgvM7wSIIvPl94Mqted863WeiDOuRVt&state=YXgvM7wSIIvPl94Mqted863WeiDOuRVt&response_type=code" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
```

The domain name is4.local is self signed. I tried to add the certificate (incuding root CA) in /app/data/ssl but I got the same error.

Is there a way to deactivate the social auth SSL verification ? (as it is only on dev environment that the certificate is self signed). Or do you have an idea on how to add the certificate ?

Thanks.

```
      volumeMounts:
        - mountPath: /app/data
          name: weblate-data
        - mountPath: /app/data/ssl
          name: certificates
      volumes:
        - name: weblate-data
          persistentVolumeClaim:
           claimName: weblate-data
        - name: certificates
          secret:
            secretName: tls-secret-is4
```

```
apiVersion: v1
data:
  tls.crt: xxx
  tls.key: yyy
kind: Secret
metadata:
  name: tls-secret-is4
type: kubernetes.io/tls
```

```$weblate@weblate-6db64c748c-m8jb6:/$ ls -ail /app/data/ssl
total 4
2 drwxrwsrwt  3 root weblate  120 Dec 11 11:40 .
2 drwxrwsr-x 17 root weblate 4096 Dec 11 11:40 ..
3 drwxr-sr-x  2 root weblate   80 Dec 11 11:40 ..2019_12_11_11_40_09.025899364
8 lrwxrwxrwx  1 root root      31 Dec 11 11:40 ..data -> ..2019_12_11_11_40_09.025899364
7 lrwxrwxrwx  1 root root      14 Dec 11 11:40 tls.crt -> ..data/tls.crt
6 lrwxrwxrwx  1 root root      14 Dec 11 11:40 tls.key -> ..data/tls.key
```
