### ISSUE TITLE
Static files broken after upgrading from 3.9 to 3.10

### ISSUE THREAD

**Issue by loktionovam** [WeblateOrg/docker#495]
**Describe bug**

After upgrading weblate from `weblate/weblate:3.9.1-2` to `weblate/weblate:3.10-1` the web interface was broken

**To Reproduce**

* Deploy `weblate/weblate:3.9.1-2` via docker-compose as described here https://github.com/WeblateOrg/docker-compose
```bash
docker-compose up -d
```
 ```yaml
version: '3'
services:
  weblate:
    image: weblate/weblate:3.9.1-2
    volumes:
      - weblate-data:/app/data
    ports:
      - "80:8080"
      - "443:4443"
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:11-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```
* Upgrade weblate version to `weblate/weblate:3.10-1`
```yaml
diff --git a/docker-compose.yml b/docker-compose.yml
index 30c4dff..580b5b9 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,9 +1,12 @@
 version: '3'
 services:
   weblate:
-    image: weblate/weblate:3.9.1-2
+    image: weblate/weblate:3.10-1
     volumes:
       - weblate-data:/app/data
+    ports:
+      - "80:8080"
+      - "443:4443"
     env_file:
       - ./environment
     restart: always
```
```bash
docker-compose up -d
```

**Expected behavior**

There should be an updated interface from version 3.10 and there are no manual step besides pulling latest version as described here https://docs.weblate.org/en/weblate-3.10/admin/upgrade.html

**Actual behavior**

Web interface is broken - some parts of ui from 3.9 another parts from 3.10
![weblate_3_10](https://user-images.githubusercontent.com/24241455/71581759-ce15d180-2b17-11ea-8a5e-29cfa518b6f3.png)

**Additional context**

**Possible root cause** https://github.com/WeblateOrg/docker/blob/master/start entrypoint script don't use `--clear` option to regenerate static files in `/app/data/static/` directory

```bash
   # this
    run_weblate collectstatic --noinput
  # should be
    run_weblate collectstatic --noinput --clear
```

Weblate logs during container migration:

```
77 static files copied to '/app/data/static', 272 unmodified.
```

**Workaround** use non-persistent `/app/data/static` sub-directory (exclude that directory from volume mount), so static files will be generated after each container restart

```bash
FROM weblate/weblate:3.10-1

RUN mkdir -p /app/data/static/ \
    && chown 1000:1000 /app/data/static/
```

```yaml
    image: weblate:3.10-1-local
    build: ./docker/weblate/
    volumes:
      - weblate-data:/app/data
      - ./settings-override.py:/app/data/settings-override.py
      # Exclude '/app/data/static/' sub-dir from volume mount due to bug
      # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      - /app/data/static/

```
