### ISSUE TITLE
Set Weblate version

### ISSUE THREAD

**Issue by mfelmy** [WeblateOrg/docker#502]
I've installed Weblate using Docker and want to access a private repository on GitLab. If I try to add a component I get a `Could not fetch the repository: fatal: could not read Username for 'https://git.*.de': terminal prompts disabled (128)` error.

My `docker-compose.override.yml` is the following:
```yml
version: '3'
services:
    weblate:
        ports:
            - 80:8080
        
        environment:
            - WEBLATE_EMAIL_HOST=smtp.example.com
            - WEBLATE_EMAIL_HOST_USER=user
            - WEBLATE_EMAIL_HOST_PASSWORD=pass

            - WEBLATE_SERVER_EMAIL=weblate@example.com
            - WEBLATE_DEFAULT_FROM_EMAIL=weblate@example.com
            - WEBLATE_ALLOWED_HOSTS=weblate.example.com,localhost

            - WEBLATE_ADMIN_PASSWORD=1234
            - WEBLATE_ADMIN_EMAIL=weblate.admin@example.com

            - WEBLATE_GITLAB_USERNAME=***
            - WEBLATE_GITLAB_HOST=git.*.de
            - WEBLATE_GITLAB_TOKEN=***
```

From the documentation I get that some features regarding [GitLab](https://docs.weblate.org/en/weblate-3.10/vcs.html#gitlab) are new to Weblate version 3.9.

Following the documentation for installing Weblate with Docker and given the above mentioned `docker-compose.override.yml` I end up having Weblate version 3.1, as set [here](https://github.com/WeblateOrg/docker/blob/562325c4366272386a1f6101bcfdda5880a94958/Dockerfile#L3).

So my question is, how to set a specific (or latest) version for Weblate using Docker?
