### ISSUE TITLE
in Docker(idk), mass upload for web is 504, and zip upload is same

### ISSUE THREAD

**Issue by readingsnail** [WeblateOrg/docker#598]
i wanna uploaded to 1.6 Mb (54~150) files in source code repo(https://github.com/readingsnail/stellaris - git@github.com:readingsnail/stellaris.git) and branch, weblate is print 504, and not maked error messages. only took for this. zip file upload is same, it's 413 message. so what i upload my translation files?

```
weblate_1   | uwsgi stderr | INFO europa-cafe/stellaris: rebase remote into repo 006040bb402f45b62527ed8cf69f19d9c41b49fa..006040bb402f45b62527ed8cf69f19d9c41b49fa
weblate_1   | uwsgi stderr | INFO europa-cafe/stellaris: updating repository
weblate_1   | uwsgi stderr | INFO europa-cafe/stellaris: update took 4.14 seconds
weblate_1   | uwsgi stderr | INFO europa-cafe/stellaris: repository updated from 006040bb402f45b62527ed8cf69f19d9c41b49fa to 006040bb402f45b62527ed8cf69f19d9c41b49fa
weblate_1   | uwsgi stderr | DEBUG europa-cafe/stellaris: update: 006040bb402f45b62527ed8cf69f19d9c41b49fa
weblate_1   | uwsgi stderr | INFO europa-cafe/stellaris: rebase remote into repo 006040bb402f45b62527ed8cf69f19d9c41b49fa..006040bb402f45b62527ed8cf69f19d9c41b49fa
weblate_1   | uwsgi stderr | [pid: 336|app: 0|req: 6/12] 172.19.0.1 () {40 vars in 523 bytes} [Tue Apr  7 15:26:34 2020] GET / => generated 0 bytes in 5 msecs (HTTP/1.0 301) 5 headers in 222 bytes (1 switches on core 0)
weblate_1   | nginx stdout | 172.19.0.1 - - [07/Apr/2020:15:26:34 +0900] "GET / HTTP/1.0" 301 0 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"
weblate_1   | uwsgi stderr | [pid: 336|app: 0|req: 7/13] 172.19.0.1 () {40 vars in 523 bytes} [Tue Apr  7 15:26:37 2020] GET / => generated 0 bytes in 0 msecs (HTTP/1.0 301) 5 headers in 222 bytes (1 switches on core 0)
weblate_1   | nginx stdout | 172.19.0.1 - - [07/Apr/2020:15:26:37 +0900] "GET / HTTP/1.0" 301 0 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"
```

[en.zip](https://github.com/WeblateOrg/docker/files/4442425/en.zip) - is here for my zip(original) file

and, my override files (+using nginx for reverse proxy, for other app's compatibility and let's encrypt problem)

```
version: '3'
services:
  weblate:
    ports:
      - 8080:8080
    environment:
      WEBLATE_EMAIL_HOST: 
      WEBLATE_EMAIL_HOST_USER: 
      WEBLATE_EMAIL_HOST_PASSWORD: 
      WEBLATE_SERVER_EMAIL: 
      WEBLATE_DEFAULT_FROM_EMAIL:
      WEBLATE_ALLOWED_HOSTS: translate.readingsnail.pe.kr,weblate
      WEBLATE_ADMIN_PASSWORD: 
      WEBLATE_ADMIN_EMAIL: 
      WEBLATE_TIME_ZONE: Asia/Seoul
      WEBLATE_AKISMET_API_KEY: 
      WEBLATE_MT_MICROSOFT_COGNITIVE_KEY: 
```
