### ISSUE TITLE
Any plans to make this ready for docker swarm mode?

### ISSUE THREAD

**Issue by rdxmb** [WeblateOrg/docker#65]
**This is a feature request.**

Hi, deploying this with '''docker stack''' is not ready yet. Docker swarm mode needs 

- docker-compose file version 3.x 
- replacing docker legacy links with docker network features

That would be great. Thanks!

**Comment by nijel** [comment]
Patches are welcome :-). There might be some problems with running tests as I'm not sure if the 3.x file is supported by tools on Travis CI (but that could probably be resolved).

**Comment by westfood** [comment]
Maybe this will help someone.

We run 2.20 in swarm mode. This is our Jinja template for Ansible, so you should fix curly braces in environment definition. We use our Docker image, but we will use upstream build once this commit is part of the build: https://github.com/WeblateOrg/docker/commit/74bbc76bef4c01508cde680b0d5a4d5dda57eb2a. 

We will also remove memcached container from compose definition, as we stick with elasticache cluster provided by AWS.

```
version: "3.4"

volumes:
  weblate:
    driver: cloudstor:aws

services:
  cache:
    image: memcached:latest
    hostname: weblate-cache-prod
    deploy:
      placement:
        constraints: [ node.role == worker ]
      labels:
        com.nekde.name: memcached
        com.nekde.env: swarm-prod
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

  web:
#    image: weblate/weblate:${WEBLATE_VERSION}
    image: nekde/weblate:2.20
    hostname: weblate-prod
    ports:
      - 8013:80
    volumes:
      - weblate:/app/data
    deploy:
      placement:
        constraints: [ node.role == worker ]
      labels:
        com.nekde.name: weblate
        com.nekde.env: swarm-prod
      resources:
        limits:
          cpus: '0.20'
          memory: 1024M
        reservations:
          cpus: '0.20'
          memory: 1024M
    environment:
      # See Weblate documentation for detailed description:
      # https://docs.weblate.org/en/latest/admin/deployments.html#docker

      # Weblate setup
      WEBLATE_DEBUG: 1
      WEBLATE_LOGLEVEL: DEBUG
      WEBLATE_SITE_TITLE: Weblate
      WEBLATE_ADMIN_NAME: Weblate Admin
      WEBLATE_ADMIN_EMAIL: dev@nekde.com
      WEBLATE_ADMIN_PASSWORD: {{ WEBLATE_ADMIN_PASSWORD }}
      WEBLATE_SERVER_EMAIL: noreply@weblate.org
      WEBLATE_DEFAULT_FROM_EMAIL: dev@nekde.com
      WEBLATE_ALLOWED_HOSTS: '*'
      WEBLATE_REGISTRATION_OPEN: 1

      # Extra
      WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: {{ WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
      WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: {{ WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}

      # This have to be defined or Redis will be used
      MEMCACHED_HOST: cache

      # PostgreSQL setup
      POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
      POSTGRES_USER: weblate
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: pgsql-na1.nekdecom
      POSTGRES_PORT:

      # Mail server, the server has to listen on port 587 and understand TLS
      WEBLATE_EMAIL_HOST: nekde.org
      # Do NOT use quotes here
      WEBLATE_EMAIL_USER: postmaster@nekde.com
      # Do NOT use quotes here
      WEBLATE_EMAIL_PASSWORD: {{ WEBLATE_EMAIL_PASSWORD }}

```
