### ISSUE TITLE
LDAPS Authentication doesn't work 

### ISSUE THREAD

**Issue by azuron** [WeblateOrg/docker#703]
Hello! Does LDAPS weblate authorization support in the docker build?

If I try to log in via LDAPS, authorization does not work.
'WEBLATE_AUTH_LDAP_SERVER_URI: ldaps://ldap.example.org'

Authorization via LDAP works perfectly.

**Comment by nijel** [comment]
Any errors in the logs? I see no reason why it should not work. Maybe SSL certificate validation issues?

**Comment by azuron** [comment]
No, there are no LDAP errors in the logs. There are other errors:

You have not set the SECURE_HSTS_INCLUDE_SUBDOMAINS setting to True. Without this, your site is potentially vulnerable to attack via an insecure connection to a subdomain. Only set this to True if you are certain that all subdomains of your domain should be served exclusively via SSL.

Backups are not configured, it is highly recommended for production use

Error collection is not set up, it is highly recommended for production use

You should not have DEBUG set to True in deployment.

**Comment by azuron** [comment]
My configuration looks like this:
```
environment:
  WEBLATE_AUTH_LDAP_SERVER_URI: ldaps://ldap.example.org
  WEBLATE_AUTH_LDAP_BIND_DN: CN=ldap,CN=Users,DC=example,DC=com
  WEBLATE_AUTH_LDAP_BIND_PASSWORD: password
  WEBLATE_AUTH_LDAP_USER_ATTR_MAP: full_name:name,email:mail
  WEBLATE_AUTH_LDAP_USER_SEARCH: CN=Users,DC=example,DC=com
  WEBLATE_AUTH_LDAP_USER_SEARCH_FILTER: (sAMAccountName=%(user)s)
```
