### ISSUE TITLE
Nginx reverse proxy for Weblate

### ISSUE THREAD

**Issue by azuron** [WeblateOrg/docker#709]
Hello! Please tell me how to configure Nginx reverse proxy for the Weblate container? Nginx is located on the host system and accepts https traffic and sends it to the Weblate container on port 8080.
The Nginx config looks like this:
```
server {
    listen 80 default_server;
    server_name $_;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    ssl_protocols TLSv1.2;

    server_name $_;

    client_max_body_size 1024m;

    ssl_certificate     /etc/nginx/ssl/server.cert;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;

    location / {
	proxy_pass http://localhost:8080;
    }
}
```

docker-compose.yml
```
version: '3'
services:
  weblate:
    image: weblate/weblate
    volumes:
      - /srv/weblate/data:/app/data
    restart: always
    ports:
      - 8080:8080
    networks:
      - weblate_net
    environment:
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
      WEBLATE_ALLOWED_HOSTS: weblate.mydomain.com,localhost
      POSTGRES_HOST: 192.168.1.20
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: weblate
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: password
    depends_on:
      - cache
  cache:
    image: redis:5-alpine
    networks:
      - weblate_net
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  redis-data: {}

networks:
  weblate_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
```

When connecting via the browser, I get the error ERR_TOO_MANY_REDIRECTS.
There are a lot of messages in Nginx logs:
```
192.168.1.5 - - [24/Jun/2020:12:36:17 +0300] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
192.168.1.5 - - [24/Jun/2020:12:36:17 +0300] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
192.168.1.5 - - [24/Jun/2020:12:36:17 +0300] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
```

Logs in the Weblate container:
```
nginx stdout | 172.18.0.1 - - [24/Jun/2020:12:26:06 +0300] "GET / HTTP/1.0" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
nginx stdout |
nginx stdout | 172.18.0.1 - - [24/Jun/2020:12:26:06 +0300] "GET / HTTP/1.0" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
nginx stdout |
nginx stdout | 172.18.0.1 - - [24/Jun/2020:12:26:06 +0300] "GET / HTTP/1.0" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
```
Maybe I made a mistake in configuring the Weblate container?
